export const palette = {
	primaryColor: '#1976D2',
	primaryVariantColor: '#1565C0',
	secondaryColor: '#BBDEFB',
	secondaryVariantColor: '#90CAF9',
	backgroundColor: '#121212',
	surfaceColor: '#1E1E1E',
	errorColor: '#B00020',
	onPrimaryColor: '#FFFFFF',
	onSecondaryColor: '#000000',
	onBackgroundColor: '#FFFFFF',
	onSurfaceColor: '#FFFFFF',
	onErrorColor: '#FFFFFF',
	dividerColor: '#BDBDBD',
	disabledColor: '#636363',
	accentColor: '#FFC107',
	accentVariantColor: '#FFA000',
	textColor: '#FFFFFF',
	subtitleColor: '#BDBDBD',
	captionColor: '#9E9E9E',
	linkColor: '#4DA6FF',
};
